name: Daily Ingestion to BigQuery

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # On passe à 3.10 pour être à jour

      - name: Install dependencies
        run: pip install requests pandas google-cloud-bigquery pandas-gbq pyarrow

      - name: Authenticate with JSON Key
        run: |
          # Cette syntaxe est plus sûre pour écrire des secrets multi-lignes
          cat <<EOF > gcp_key.json
          ${{ secrets.GCP_SA_KEY }}
          EOF
          echo "GOOGLE_APPLICATION_CREDENTIALS=$GITHUB_WORKSPACE/gcp_key.json" >> $GITHUB_ENV
          
      - name: 'Run ingestion script'
        env:
          PYTHONUNBUFFERED: "1"
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp_key.json
        run: python ingestion.py
